apiVersion: skaffold/v2beta2
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nayeemnishaat/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: . # Note: dest: . means sync the src: "src/**/*.ts" files inside the running container's corresponding path.
    - image: nayeemnishaat/client
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: nayeemnishaat/ticket
      context: ./ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: nayeemnishaat/order
      context: ./order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
