apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: nayeemnishaat/payment
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-svc:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://payment-mongo-svc:27017/payment"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: STRIPE_KEY
          resources:
            limits:
              memory: 500Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
# Type is not defined, so it will be ClusterIP by default
metadata:
  name: payment-svc
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 3000 # Host
      targetPort: 3000 # Pod
