name: deploy-order

on:
  push:
    branches:
      - main
    paths:
      - "order/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd order && docker build -t nayeemnishaat/order .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push nayeemnishaat/order
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save CLUSTER_NAME
      - run: kubectl rollout restart deployment order-depl
