name: test-ticket

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticket && npm i && npm run test:ci # cd in respect of root of git repo (.gitignore).
